### ISSUE TITLE
.env

### ISSUE THREAD

**Issue by CzCraft27** [RocktimSaikia/anime-chan#14]
It is the first time that I am testing this of node js and some of its technologies and I wanted to try this but something related to the .env does not let me work.

C:\Users\Js\Documents\GitHub\anime-chan\node_modules\mongoose\lib\connection.js:579
    throw new MongooseError('The `uri` parameter to `openUri()` must be a ' +
    ^
Error [MongooseError]: The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.
    at new MongooseError (C:\Users\Js\Documents\GitHub\anime-chan\node_modules\mongoose\lib\error\mongooseError.js:10:11)
    at NativeConnection.Connection.openUri (C:\Users\Js\Documents\GitHub\anime-chan\node_modules\mongoose\lib\connection.js:579:11)
    at Mongoose.connect (C:\Users\Js\Documents\GitHub\anime-chan\node_modules\mongoose\lib\index.js:333:15)
    at Object.<anonymous> (C:\Users\Js\Documents\GitHub\anime-chan\server.js:14:10)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
[nodemon] app crashed - waiting for file changes before starting...

**Comment by RocktimSaikia** [comment]
there are two branches of this api .The github master branch and one local production branch which is used for the live api not this github master branch. Also the original mongoDB uri is not present in this master branch because of security issues. So if you want to play or test with the repo you have create an `.env` file with your own local mongoDB URI and seed some initial quotes with the schema model present on the project before hand.
